name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies (if needed)
      run: |
        pip install -r requirements.txt

    - name: Build Docker image
      run: |
        docker build -t iris .

    #- name: Check secrets
    #  run: echo "Username length: ${#${{ secrets.DOCKER_HUB_USERNAME }}}"

    #- name: Check Docker version
    #  run: docker --version
    #- name: Log in to Docker Hub
    # uses: docker/login-action@v2
     # with:
     #    username: ${{ secrets.DOCKER_HUB_USERNAME }}
     #    password: ${{ secrets.DOCKER_HUB_PASSWORD }}


    - name: Log in to Docker Hub
     # run: docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" -p "${{ secrets.DOCKER_HUB_PASSWORD }}"   
      run: echo "${{ secrets.DOCKER_HUB_PASSWOD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

    - name: Tag Docker image
      run: docker tag iris:latest pushkar243/iris:latest

    - name: Push Docker image to Docker Hub
      run: docker push pushkar243/iris:latest

    - name: Test Docker container locally
      run: |
        docker run -d -p 8501:8501 pushkar243/iris:latest